version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - COMMIT="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - BUILD_URL="${REPOSITORY_URL}:${COMMIT}"

  build:
    commands:
      - printf '{"Parameters":{"CommitHash":"%s"}}' "$COMMIT" > build.hash.json
      - cd src/part3/application
      - docker-compose run --rm hadolint < Dockerfile
      - docker-compose build --pull --parallel
      - docker-compose run --rm trivy --auto-refresh $REPOSITORY_URL
      - docker-compose run --rm cli ./vendor/bin/phpunit --testdox

  post_build:
    commands:
      - if expr "$CODEBUILD_BUILD_SUCCEEDING" = "0"; then exit 1; fi
      - docker tag $REPOSITORY_URL $BUILD_URL
      - docker push $REPOSITORY_URL

artifacts:
  files:
    - build.hash.json
