version: '3.4'

services:
  app:
    image: ipc:full
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      APP_ENV: local

  cli:
    image: ipc:full-cli
    build:
      context: .
      target: cli
    command: sh
    volumes:
      - ./:/app
    environment:
      APP_ENV: local

  node:
    image: ipc:full-node
    build:
      context: .
      target: node
    volumes:
      - ./:/app

  worker:
    image: ipc:full-worker
    build:
      context: .
      target: worker
    volumes:
      - ./:/app
    environment:
      APP_ENV: local
