version: '3.4'

services:
  app:
    image: phpday:alpine
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment: 
      APP_ENV: local

  cli:
    image: phpday:alpine-cli
    build:
      context: .
      target: cli
    command: sh
    volumes:
      - ./:/app
    environment: 
      APP_ENV: local
