version: '3.4'

services:
  app:
    image: talk:alpine
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      APP_ENV: local

  cli:
    image: talk:alpine-cli
    build:
      context: .
      target: cli
    command: sh
    volumes:
      - ./:/app
    environment:
      APP_ENV: local
