version: '3.4'

services:
  app:
    image: 250478887320.dkr.ecr.us-east-1.amazonaws.com/talk
    build: .
    ports:
      - 80:80
    environment:
      APP_ENV: local

  cli:
    image: 250478887320.dkr.ecr.us-east-1.amazonaws.com/talk:cli
    build:
      context: .
      target: cli
    command: echo 'cli service disabled'
    environment:
      APP_ENV: testing

  hadolint:
    image: hadolint/hadolint
    command: hadolint --ignore DL3018 -

  trivy:
    image: aquasec/trivy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache:/root/.cache
