FROM php:7.2-apache

WORKDIR /app 

COPY . /app

RUN apt-get update \
 && apt-get install -y unzip \
 && docker-php-ext-install pdo_mysql opcache \
 && curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer \
 && composer install --no-dev \
 && a2enmod rewrite \
 && chown -R www-data:www-data /app/storage /app/bootstrap/cache

COPY docker /
